include: ['_pages', '_css', '_scripts', '_images']

title: Battle Spot Damage Calculator

github:
  repository_url: https://github.com/cantsay/cantsay.github.io/
  owner_name: cant say
  owner_url: https://github.com/cantsay/
  
url: "https://cantsay.github.io"
  
repository: cantsay/cantsay.github.io

description:
  Pokemon Damage Calculator for Gen 5, 6, and 7 BSS and competitive LGPE, preloaded with viable sets for all formats.
  

plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from
